{{- $languageValues := deepCopy .Values }}
{{- $jobKind := (default $languageValues.kind) -}}
{{ if (and $jobKind (eq $jobKind "CronJob")) }}
{{ range $languageValues.crons }}
{{ $_  := set . "releaseNameOverride" .cronJobName}}
{{- $merge := mergeOverwrite $.Values . }}
{{- $root := mergeOverwrite $ $merge }}
---
apiVersion: batch/v1beta1
kind: CronJob
{{ include "hmcts.metadata.v2" $ }}
spec:
  schedule: "{{ .schedule }}"
  {{- if .startingDeadlineSeconds }}
  startingDeadlineSeconds: {{int .startingDeadlineSeconds }}
  {{- end }}
  {{- if .concurrencyPolicy }}
  concurrencyPolicy: {{ .concurrencyPolicy }}
  {{- end }}
  {{- if .successfulJobsHistoryLimit }}
  successfulJobsHistoryLimit: "{{ .successfulJobsHistoryLimit }}"
  {{- end }}
  {{- if .failedJobsHistoryLimit }}
  failedJobsHistoryLimit: "{{ .failedJobsHistoryLimit }}"
  {{- end }}
  {{- if .suspend }}
  suspend: {{ .suspend }}
  {{- end }}
  jobTemplate:
{{ include "job.spec" $root  | indent 4 }}
{{- end -}}
{{- end}}