apiVersion: batch/v1
kind: CronJob
metadata:
  name: vh-anonymise-hearings-conferences-and-delete-aad-users-job
spec:
  schedule: "0 30 5 * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: vh-anonymise-hearings-conferences-and-delete-aad-users-job
              image: sdshmctspublic.azurecr.io/vh/scheduler-jobs-sds:latest
              args: ["AnonymiseHearingsConferencesAndDeleteAadUsersJob"]
              env:
          restartPolicy: Never