name: $(Date:yyyyMMddHHmm)-$(Rev:r)

resources:
  repositories:
    - repository: azTemplates
      type: github
      name: hmcts/azure-devops-templates
      ref: master
      endpoint: hmcts
      
trigger: none

pr:
  - master

pool: 
  vmImage: ubuntu-22.04

Steps:
- bash: |
    echo "hello"
