name: $(Date:yyyyMMddhhmm)-$(Rev:r)

resources:
  repositories:
    - repository: azTemplates
      type: github
      name: hmcts/azure-devops-templates
      ref: master
      endpoint: hmcts
      
trigger: none

pr:
  - master

variables:
  - group: vh-github-app-credentials
  - name: app_path
    value: 'SchedulerJobs'
  - group: vh-scheduler-jobs
  - name: run_acceptance_tests
    value: false

stages:
#####################################################
# CI Build Checks. ##################################
  - stage: CI_Build
    displayName: CI Build
    variables: 
      - template: variables/shared.yaml
        parameters:
          env: ''
    jobs:
      - job: CI_Helm
        displayName: "Helm CI"
        steps:
          - checkout: self

          - template: templates\Containerisation\helm\helm-lint.yaml@azTemplates
            parameters:
              chartPath: ${{ variables.chartPath }}
              chartValuesPath: ${{ variables.chartPath }}

      - job: UnitTests
        displayName: "Unit Tests"
        steps:
          - checkout: self
          
          - template: stages\dotnet-tests\unit-tests.yml@azTemplates
            parameters:
              nugetConfigPath: ${{ variables.app_path }}
              unitTestProjectPath: "${{ variables.app_path }}/${{ variables.app_path }}.UnitTests"
              coverletCoverageExclusions:
                - "[${{ variables.app_path }}.*Tests?]*"
                - "[${{ variables.app_path }}]Startup"
                - "[*]${{ variables.app_path }}.Common.*"
                - "[Testing.Common]*"

      - job: SonarCloud
        displayName: SonarCloud Test Analysis
        steps:
          - template: templates/sonarCloud/prepare.yml@azTemplates
            parameters:
              sonarCloud_ExtraProperties: |
                sonar.cs.opencover.reportsPaths=$(Common.TestResultsDirectory)\Coverage\coverage.opencover.xml
                sonar.coverage.exclusions=${{ variables.sonar_exclusion }}

          - bash: |
              cd SchedulerJobs/SchedulerJobs.UnitTests
              dotnet build SchedulerJobs.UnitTests.csproj
            displayName: Build .NET Project(s)

          - template: templates/sonarCloud/runAnalysis.yml@azTemplates

#####################################################
# Pre Steps. ########################################
# Build Docker Image & Generate EF Script. ##########
  - stage: Dock
    displayName: Build API
    dependsOn: CI_Build
    variables: 
      - group: aks-cluster-info
      - template: variables/dev.yaml
      - template: variables/shared.yaml
        parameters:
          env: ${{ variables.env }}
      - group: vh-github-app-credentials
    jobs:
      - job: Dock
        displayName: "Build and Push Image ${{ variables.git_repo_name }}"
        steps:
          - checkout: self

          - template: templates\Github\get-app-token.yaml@azTemplates
            parameters:
              privateKeyFileName: ${{ variables.gh_app_private_key_file_name }}
              appId: $(gh_app_app_id)

          - template: templates\Github\bump-chart-versions.yaml@azTemplates
            parameters:
              chartName: ${{ variables.chartName }}
              chartPath: $(Build.SourcesDirectory)
              chartBranch: $(System.PullRequest.SourceBranch)
              githubToken: $(githubappinstall.token)
              githubUsername: $(gh_app_name)
              githubEmail: "$(gh_app_app_id)+$(gh_app_name)[bot]@users.noreply.github.com"
          
          - bash: |
              sed -i "s|</configuration>|<packageSourceCredentials><vh-packages><add key=\"Username\" value=\"PAT\" /><add key=\"ClearTextPassword\" value=\"$(System.AccessToken)\" /></vh-packages></packageSourceCredentials></configuration>|" nuget.sds.config
            displayName: Add NuGet Feed Authentication
            workingDirectory: SchedulerJobs

          - template: templates\Containerisation\docker\docker-compose.yaml@azTemplates
            parameters:
              azureSubscription: ${{ variables.acrSubscription }}
              acrName: ${{ variables.acrName }}
              repositoryName:  ${{ variables.repositoryName }}

          - template: templates\Containerisation\docker\docker-push-azure.yaml@azTemplates
            parameters:
              azureSubscription: ${{ variables.acrSubscription }}
              acrName: ${{ variables.acrName }}
              repositoryName:  ${{ variables.repositoryName }}
              imageName: "${{ replace(variables.git_repo_name, '-', '') }}"
              imageTags:
                - '${{ variables.prTagName }}'

      - job: package_nuget
        displayName: "Package NuGet Packages"
        dependsOn: Dock
        steps:
          - template: templates\dotnet\package-nuget-packages.yml@azTemplates
            parameters:
              nugetProjectPath: "SchedulerJobs/${{ variables.nuget_package_name }}"
              vstsFeed: "${{ variables.nuget_org_name }}/${{ variables.nuget_feed_name }}"
              gitVersionConfigPath: ${{ variables.git_version_config_path }}

      - ${{ if eq(variables.run_acceptance_tests, true) }}:
        - job: PublishAcceptanceTests
          displayName: Publish Acceptance Tests 
          variables:
            projectPath: SchedulerJobs/SchedulerJobs
          steps:
          - template: templates\dotnet\publish-acceptance-tests.yml@azTemplates
            parameters:
              coreProjectPath: $(projectPath)
              nugetProjectPath: $(projectPath)

#####################################################
# Deploy Helm Chart to Dev. ######################### 
  - stage: Install
    dependsOn: Dock
    displayName: Deploy Helm Chart Dev AKS
    variables:
      - template: variables/dev.yaml
      - template: variables/shared.yaml
        parameters:
          env: ${{ variables.env }}
      - name: dnsRecordName
        value: vh-${{ variables.git_repo_name }}-${{ variables.prTagPrefix }}
    jobs:
      - job: helm_uninstall
        displayName: Uninstall Helm from Dev
        steps:

          - template: templates\Azure\Aks\get-active-cluster.yaml@azTemplates
            parameters:
              subscriptionName: "${{ variables.subscriptionName }}"
              environment: ${{ variables.env }}
            
          - template: templates/Containerisation/helm/helm-uninstall.yaml@azTemplates
            parameters:
              namespace: 'vh'
              releaseName: "${{ variables.chartName }}-${{ variables.prTagPrefix }}"
              azureSubscription: "${{ variables.subscriptionName }}"
              aksResourceGroupName: "$(aksCluster.resourceGroup)"
              aksClusterName: "$(aksCluster.name)"
      - job: aks_push
        displayName: Deploy To Dev AKS
        steps:

          - template: templates\Azure\Aks\get-active-cluster.yaml@azTemplates
            parameters:
              subscriptionName: "${{ variables.subscriptionName }}"
              environment: ${{ variables.env }}
          - template: templates/Containerisation/helm/helm-install.yaml@azTemplates
            parameters:
              privateKeyFileName: ${{ variables.gh_app_private_key_file_name }}
              appId: $(gh_app_app_id)
              envValuesTemplatePath: ${{ variables.envValuesTemplatePath }}
              envValuesPath: ${{ variables.envValuesPath }}
              acrName: ${{ variables.acrName }}
              repositoryName: ${{ variables.repositoryName }}
              prTagName: ${{ variables.prTagName }}
              releaseName: "${{ variables.chartName }}-${{ variables.prTagPrefix }}"
              dnsRecordName: ${{ variables.dnsRecordName }}
              dnsZone: ${{ variables.dnsZone }}
              env: ${{ variables.env }}
              chartName: ${{ variables.chartName }}
              chartPath: ${{ variables.chartPath }}
              subscriptionName: "${{ variables.subscriptionName }}"
              aksResourceGroupName: "$(aksCluster.resourceGroup)"
              aksClusterName: "$(aksCluster.name)"
              dnsSubscriptionName: "${{ variables.dnsZoneSubscription }}"
              dnsResourceGroupName: "${{ variables.dnsZoneResourceGroup }}"

      - ${{ if eq(variables.run_acceptance_tests, true) }}:
        - job: AcceptanceTestsDev
          displayName: Acceptance Tests Dev
          steps:
          - template: templates/dotnet/run-acceptance-tests.yml@azTemplates
            parameters:
              environment: ${{ variables.env }}
              azureSubscription: ${{ variables.subscriptionName }}
              acceptanceTestSettings:
                - name: Services:SchedulerJobsUrl
                  value: "https://vh-scheduler-jobs.dev.platform.hmcts.net"
                - name: ApplicationInsights:InstrumentationKey
                  value: applicationinsights--instrumentationkey
                  keyVaultName: vh-infra-core-${{ variables.env }}
                  secret: true
                - name: AzureAd:ClientId
                  value: azuread--clientid
                  keyVaultName: vh-scheduler-jobs-${{ variables.env }}
                  secret: true
                - name: AzureAd:ClientSecret
                  value: azuread--clientsecret
                  keyVaultName: vh-scheduler-jobs-${{ variables.env }}
                  secret: true
                - name: AzureAd:TenantId
                  value: azuread--tenantid
                  keyVaultName: vh-infra-core-${{ variables.env }}
                  secret: true

                # Services Configuration
                - name: Services:SchedulerJobsResourceId
                  value: azuread--identifieruri
                  keyVaultName: vh-scheduler-jobs-${{ variables.env }}
                  secret: true
                - name: Services:CallbackUri
                  value: $(CallbackUri)
                       
#####################################################
# Deploy Nuget Packages. #########################
  - stage: Push_Nuget
    dependsOn: Install
    displayName: Deploy NuGet Packages
    variables:
      - template: variables/dev.yaml
      - template: variables/shared.yaml
        parameters:
          env: ${{ variables.env }}
    jobs: 
      - job: Publish_Nuget
        displayName: Publish NuGet Packages
        steps:
          - template: templates\dotnet\push-nuget-packages.yml@azTemplates
            parameters:
              vstsFeed: "${{ variables.nuget_org_name }}/${{ variables.nuget_feed_name }}"

#####################################################
# Manual Approval To Demo. ##########################
  - stage: Wait
    dependsOn: Push_Nuget
    jobs:
      - job: Wait
        displayName: "Approve Release Demo"
        pool: server
        steps:
          - task: ManualValidation@0
            timeoutInMinutes: 1440 # task times out in 1 day
            inputs:
              instructions: 'Please approve the release of PR-$(System.PullRequest.PullRequestNumber) to the Demo environment to resume'
              onTimeout: 'reject'

#####################################################
# Deploy Helm Chart to QA. ##########################
  - stage: Install_Demo
    displayName: Deploy Helm Chart Demo AKS
    dependsOn: Wait
    variables:
      - template: variables/qa.yaml
      - template: variables/shared.yaml
        parameters:
          env: ${{ variables.env }}
      - name: dnsRecordName
        value: vh-${{ variables.git_repo_name }}-${{ variables.prTagPrefix }}
    jobs:
      - job: helm_uninstall
        displayName: Uninstall Helm from Demo
        steps:
          - template: templates\Azure\Aks\get-active-cluster.yaml@azTemplates
            parameters:
              subscriptionName: "${{ variables.subscriptionName }}"
              environment: ${{ variables.env }}
              
          - template: templates/Containerisation/helm/helm-uninstall.yaml@azTemplates
            parameters:
              namespace: 'vh'
              releaseName: "${{ variables.chartName }}-${{ variables.prTagPrefix }}"
              azureSubscription: "${{ variables.subscriptionName }}"
              aksResourceGroupName: "$(aksCluster.resourceGroup)"
              aksClusterName: "$(aksCluster.name)"
      - job: aks_push
        displayName: Deploy To Demo AKS
        steps:
        - template: templates\Azure\Aks\get-active-cluster.yaml@azTemplates
          parameters:
            subscriptionName: "${{ variables.subscriptionName }}"
            environment: ${{ variables.env }}
        - template: templates/Containerisation/helm/helm-install.yaml@azTemplates
          parameters:
            privateKeyFileName: ${{ variables.gh_app_private_key_file_name }}
            appId: $(gh_app_app_id)
            envValuesTemplatePath: ${{ variables.envValuesTemplatePath }}
            envValuesPath: ${{ variables.envValuesPath }}
            acrName: ${{ variables.acrName }}
            repositoryName: ${{ variables.repositoryName }}
            prTagName: ${{ variables.prTagName }}
            releaseName: "${{ variables.chartName }}-${{ variables.prTagPrefix }}"
            dnsRecordName: ${{ variables.dnsRecordName }}
            dnsZone: ${{ variables.dnsZone }}
            env: ${{ variables.env }}
            chartName: ${{ variables.chartName }}
            chartPath: ${{ variables.chartPath }}
            subscriptionName: "${{ variables.subscriptionName }}"
            aksResourceGroupName: "$(aksCluster.resourceGroup)"
            aksClusterName: "$(aksCluster.name)"
            dnsSubscriptionName: "${{ variables.dnsZoneSubscription }}"
            dnsResourceGroupName: "${{ variables.dnsZoneResourceGroup }}"