name: $(Date:yyyyMMddHHmm)-$(Rev:r)

trigger:
  - master

pr: none

resources:
  repositories:
    - repository: azTemplates
      type: github
      name: hmcts/azure-devops-templates
      ref: master
      endpoint: hmcts

parameters:
- name: stages
  type: object
  default:
  - env: 'dev'
    buildPushImage: true
    pushHelmChart: true
  - env: 'demo'
    requireApproval: true
    buildPushImage: false
    pushHelmChart: false
  - env: 'test'
    requireApproval: true
    buildPushImage: true
    pushHelmChart: false
  - name: sdsUnitTestsCoverletCoverageExclusions
    type: object
    default: ["[*]SchedulerJobs.Common.*", "[*]SchedulerJobs.Sds.UnitTests.*", "[Testing.Common]*"]
  - name: servicesUnitTestsCoverletCoverageExclusions
    type: object
    default: [ "[*]SchedulerJobs.Common.*", "[*]SchedulerJobs.Services.UnitTests.*", "[Testing.Common]*" ]

pool: 
  vmImage: ubuntu-22.04

stages:
#####################################################
# CI Build Tasks. ###################################
- stage: CI_Build
  dependsOn: []
  displayName: CI Build
  variables:
  - template: variables/shared.yaml
  jobs:
  - job: UnitTests
    displayName: "Unit Tests"
    steps:
    - checkout: self

    - template: templates/sonarCloud/prepare.yml@azTemplates
      parameters:
        ExtraProperties: |
          sonar.cs.opencover.reportsPaths=$(Common.TestResultsDirectory)/Coverage/coverage.opencover.xml
          sonar.coverage.exclusions=**/VideoApiService.cs, **/Startup.cs, **/Testing.Common/**, **/SchedulerJobs.Common/ApiHelper/**, **/SchedulerJobs.Common/Helper/Configuration/**, **/SchedulerJobs.Common/Helper/Security/**

    - task: UseDotNet@2
      displayName: 'Install .NET Core SDK ${{ variables.dotnetCoreVersion }}'
      inputs:
        packageType: sdk
        version: ${{ variables.dotnetCoreVersion }}
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - powershell: |
        $dotNetLocation = (dotnet nuget locals global-packages -l).replace('global-packages: ', '')
        Write-Host "##vso[task.setvariable variable=cacheLocation;isOutput=true]$dotNetLocation"
      displayName: 'Find NuGet Cache'
      name: findCache
        
    # Scheduler Jobs Sds Unit Tests
    
    - task: Cache@2
      displayName: Scheduler Jobs Unit Tests - Cache NuGet Packages
      inputs:
        key: 'nuget | "$(Agent.OS)" | ${{ variables.app_path }}/${{ variables.app_path }}.Sds.UnitTests/packages.lock.json'
        path: $(findCache.cacheLocation)
        cacheHitVar: NUGET_CACHE_RESTORED
      
    - task: DotNetCoreCLI@2
      displayName: Scheduler Jobs Unit Tests - Restore Unit Test Project
      inputs:
        command: restore
        projects: ${{ variables.app_path }}/${{ variables.app_path }}.Sds.UnitTests/*.csproj
        restoreArguments: --force-evaluate
        ${{ if ne(variables.app_path, '') }}:
          feedsToUse: config
          nugetConfigPath: ${{ variables.app_path }}/nuget.config
        ${{ if ne(variables.vstsFeedId, '') }}:
          vstsFeed: ''
          includeNuGetOrg: true
        condition: ne(variables.NUGET_CACHE_RESTORED, 'true')

    - task: DotNetCoreCLI@2
      displayName: Scheduler Jobs Unit Tests - Run dotnet Tests
      inputs:
        testRunTitle: dotnet Tests
        command: test
        projects: |
          ${{ variables.app_path }}/${{ variables.app_path }}.Sds.UnitTests/*.csproj
        arguments: ${{ format('--configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat="\"opencover,cobertura,json,lcov\"" /p:Exclude="\"{0}\"" /p:CoverletOutput=$(Common.TestResultsDirectory)/Coverage/ /p:MergeWith=$(Common.TestResultsDirectory)/Coverage/coverage.json', join(',', parameters['sdsUnitTestsCoverletCoverageExclusions'])) }}

    # Services Unit Tests

    - task: Cache@2
      displayName: Services Unit Tests - Cache NuGet Packages
      inputs:
        key: 'nuget | "$(Agent.OS)" | ${{ variables.app_path }}/${{ variables.app_path }}.Services.UnitTests/packages.lock.json'
        path: $(findCache.cacheLocation)
        cacheHitVar: NUGET_CACHE_RESTORED

    - task: DotNetCoreCLI@2
      displayName: Services Unit Tests - Restore Unit Test Project
      inputs:
        command: restore
        projects: ${{ variables.app_path }}/${{ variables.app_path }}.Services.UnitTests/*.csproj
        restoreArguments: --force-evaluate
        ${{ if ne(variables.app_path, '') }}:
          feedsToUse: config
          nugetConfigPath: ${{ variables.app_path }}/nuget.config
        ${{ if ne(variables.vstsFeedId, '') }}:
          vstsFeed: ''
          includeNuGetOrg: true
        condition: ne(variables.NUGET_CACHE_RESTORED, 'true')

    - task: DotNetCoreCLI@2
      displayName: Services Unit Tests - Run dotnet Tests
      inputs:
        testRunTitle: dotnet Tests
        command: test
        projects: |
          ${{ variables.app_path }}/${{ variables.app_path }}.Services.UnitTests/*.csproj
        arguments: ${{ format('--configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat="\"opencover,cobertura,json,lcov\"" /p:Exclude="\"{0}\"" /p:CoverletOutput=$(Common.TestResultsDirectory)/Coverage/ /p:MergeWith=$(Common.TestResultsDirectory)/Coverage/coverage.json', join(',', parameters['servicesUnitTestsCoverletCoverageExclusions'])) }}

    ## Common

    - task: PublishCodeCoverageResults@1
      displayName: Publish Code Coverage
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: $(Common.TestResultsDirectory)/Coverage/coverage.cobertura.xml
        reportDirectory: $(Common.TestResultsDirectory)/Coverage
        failIfCoverageEmpty: true
      condition: always()

    - template: templates/sonarCloud/runAnalysis.yml@azTemplates
  
#####################################################
# Manual Approval ###################################
- ${{ each stage in parameters.stages }}:
  - stage: Manual_Approval_${{ stage.env }}
    displayName: Approval ${{ stage.env }}
    condition: eq('${{ stage.requireApproval }}', true)
    jobs:
      - job: Approve
        displayName: 'Approve to ${{ stage.env }}'
        pool: server
        timeoutInMinutes: 10080 # 7 Days
        steps:
          - task: ManualValidation@0
            timeoutInMinutes: 10080 # 7 Days
            inputs:
              instructions: 'Please Approve run to ${{ stage.env }}'
              onTimeout: 'reject'

#####################################################
# Build Docker Image & Push. ########################
  - ${{ if eq(stage.buildPushImage, true)  }}:
    - stage: Docker_Build_Push_${{ stage.env }}
      displayName: Build & Push ${{ stage.env }}
      dependsOn:
      - ${{ if stage.requireApproval }}:
        - Manual_Approval_${{ stage.env }}
      variables:
        - template: variables/${{ stage.env }}.yaml
        - template: variables/shared.yaml
      jobs:
      - job: Docker_Build_${{ stage.env }}
        displayName: Docker Build and Push ${{ stage.env }}
        steps:
        - checkout: self

        - bash: |
            sed -i "s|</configuration>|<packageSourceCredentials><vh-packages><add key=\"Username\" value=\"PAT\" /><add key=\"ClearTextPassword\" value=\"$(System.AccessToken)\" /></vh-packages></packageSourceCredentials></configuration>|" nuget.config
          displayName: Add NuGet Feed Authentication
          workingDirectory: SchedulerJobs
      
        - template: templates\Containerisation\docker\docker-compose.yaml@azTemplates
          parameters:
            azureSubscription: ${{ variables.acrSubscription }}
            acrName: ${{ variables.acrName }}
            repositoryName:  ${{ variables.repositoryName }}
            dockerComposeFile: docker-compose-sds.yml
          
        - template: templates\Containerisation\docker\docker-push-azure.yaml@azTemplates
          parameters:
            azureSubscription: ${{ variables.acrSubscription }}
            acrName: ${{ variables.acrName }}
            repositoryName:  ${{ variables.repositoryName }}
            imageName: "${{ variables.imageName }}"
            imageTags:
              - '${{ variables.imageTagName }}'

  #########################################
  # Push Helm Charts to Repo. #############
  - ${{ if eq(stage.pushHelmChart, true) }}:
    - stage: Helm_${{ stage.env }}
      displayName: Push Helm Charts ${{ stage.env }}
      dependsOn: Docker_Build_Push_${{ stage.env }}
      variables:
      - template: variables/dev.yaml
      - template: variables/shared.yaml
      - group: vh-github-app-credentials
      jobs:
      - job: Helm_${{ stage.env }}
        displayName: Helm Push ${{ stage.env }}
        steps:
        - checkout: self

        - template: templates\Github\get-app-token.yaml@azTemplates
          parameters:
            privateKeyFileName: ${{ variables.gh_app_private_key_file_name }}
            appId: $(gh_app_app_id)

        - template: templates\Github\push-to-helm-chart-repo.yaml@azTemplates
          parameters:
            chartName: ${{ variables.chartName }}
            chartPath: ${{ variables.chartPath }}
            githubToken: $(githubappinstall.token)
            githubUsername: $(gh_app_name)
            githubEmail: "$(gh_app_app_id)+$(gh_app_name)[bot]@users.noreply.github.com"
            subDirectory: ${{ variables.subDirectory }}