mode: ContinuousDelivery
ignore:
  sha: []
merge-message-formats: {}
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
commit-message-incrementing: Enabled
update-build-number: true
branches:
  main:
    regex: ^master$
    mode: ContinuousDelivery
    label: staging
    increment: Patch
    source-branches: ['feature', 'release', 'hotfix']
    is-main-branch: true
    pre-release-weight: 55000
  release:
    regex: ^releases?[/-]
    mode: ContinuousDelivery
    label: ''
    increment: None
    source-branches: ['main', 'hotfix', 'release']
    is-release-branch: true
  feature:
    regex: ^features?[/-]$
    mode: ContinuousDelivery
    label: useBranchName
    increment: Patch
    source-branches: ['pull-request', 'main', 'release', 'feature', 'hotfix']
  pull-request:
    regex: ^(pull|pull\-requests|pr)[/-]
    mode: ContinuousDelivery
    label: pr-
    increment: Patch
    label-number-pattern: '[/-](?<number>\d+)[-/]'
    source-branches: ['main', 'release', 'feature', 'hotfix']
  hotfix:
    regex: ^hotfix(es)?[/-]
    mode: ContinuousDelivery
    label: hotfix
    increment: Patch
    track-merge-target: false
    source-branches: ['pull-request', 'main', 'release']
