---
apiVersion: v2
name: vh-scheduler-jobs
home: https://github.com/hmcts/vh-scheduler-jobs
version: 0.0.2
description: Helm Chart for scheduler jobs
maintainers:
  - name: VH Devops 
dependencies:
  - name: java
    version: 3.7.9
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
