global:
  vaults:
      vh-infra-core:
        excludeEnvironmentSuffix: false
        resourceGroup: vh-infra-core-{{ .Values.global.environment }}
        usePodIdentity: true
        secrets:
          - applicationinsights--instrumentationkey
          - azuread--tenantid
          - name: azuread--appinsightskey
            alias: AppInsightsKey
          - name: storage-account-key
            alias: AzureConfiguration--StorageAccountKey
          - name: storage-account-name
            alias: AzureConfiguration--StorageAccountName
          - name: storage-account-endpoint
            alias: AzureConfiguration--StorageEndpoint
          - name: storage-account-container-elinks-name
            alias: AzureConfiguration--StorageContainerName
          - name: storage-account-web-jobs-connection-string
            alias: AzureWebJobsStorage
      vh-scheduler-jobs:
        excludeEnvironmentSuffix: false
        resourceGroup: vh-infra-core-{{ .Values.global.environment }}
        usePodIdentity: true
        secrets:
          - azuread--clientsecret
          - azuread--clientid
          - azuread--identifieruri
          - name: azuread--identifieruri
            alias: azuread--VHSchedulerJobsRESOURCEID
          - VhServices--ELinksLeaversBaseUrl
          - VhServices--ELinksPeoplesBaseUrl
          - VhServices--ELinksApiKey
          - VhServices--ELinksApiUrl
          - name: FeatureToggles--SDK-Key
            alias: FeatureToggles--SdkKey
      vh-bookings-api:
        excludeEnvironmentSuffix: false
        resourceGroup: vh-infra-core-{{ .Values.global.environment }}
        usePodIdentity: true
        secrets:
          - name: azuread--identifieruri
            alias: VhServices--BookingsApiResourceId
          - name: azuread--identifieruri
            alias: VhServices--BookingsApiUrl
      vh-video-api:
        excludeEnvironmentSuffix: false
        resourceGroup: vh-infra-core-{{ .Values.global.environment }}
        usePodIdentity: true
        secrets:
          - name: azuread--identifieruri
            alias: VhServices--VideoApiResourceId
          - name: azuread--identifieruri
            alias: VhServices--VideoApiUrl
      vh-notification-api:
        excludeEnvironmentSuffix: false
        resourceGroup: vh-infra-core-{{ .Values.global.environment }}
        usePodIdentity: true
        secrets:
          - name: azuread--identifieruri
            alias: VhServices--NotificationApiResourceId
          - name: azuread--identifieruri
            alias: VhServices--NotificationApiUrl
      vh-user-api:
        excludeEnvironmentSuffix: false
        resourceGroup: vh-infra-core-{{ .Values.global.environment }}
        usePodIdentity: true
        secrets:
          - name: azuread--identifieruri
            alias: VhServices--UserApiResourceId
          - name: azuread--identifieruri
            alias: VhServices--UserApiUrl
job:
  image: 'sdshmctspublic.azurecr.io/vh/scheduler-jobs:latest'
  kind: CronJob
  releaseNameOverride: job-1
  schedule: "30 5 * * *"
  keyVaults: "{{ .Values.global.vaults }}"
  args:
    - AnonymiseHearingsConferencesAndDeleteAadUsersJob
  environment:
    SERVICES__SCHEDULERJOBSURL: http://vh-scheduler-jobs.{{ .Values.global.environment }}.platform.hmcts.net
    Logging__LogLevel__Default: debug
    Logging__LogLevel__System: debug
    Logging__LogLevel__Microsoft: debug