---
java:
  image: 'sdshmctspublic.azurecr.io/vh/scheduler-jobs:20210311.1'
  applicationPort: 8080
  replicas: 2
  ingressHost: vh-scheduler-jobs.{{ .Values.global.environment }}.platform.hmcts.net
  releaseNameOverride: vh-scheduler-jobs
  readinessPath: /health/liveness
  livenessPath: /health/liveness
  livenessDelay: 360
  livenessPeriod: 120
  aadIdentityName: vh-aad-identity
  keyVaults:
    vh-infra-core:
      excludeEnvironmentSuffix: false
      resourceGroup: vh-infra-core-{{ .Values.global.environment }}
      usePodIdentity: true
      secrets:
        - applicationinsights--instrumentationkey
        - connectionstrings--appconfig
    vh-booking-queue:
      excludeEnvironmentSuffix: false
      resourceGroup: vh-infra-core-{{ .Values.global.environment }}
      usePodIdentity: true
      secrets:
        - azuread--clientsecret
        - azuread--clientid
  environment:
    ASPNETCORE_URLS: http://+:8080
    AZUREAD__TENANTID: "fb6e0e22-0da3-4c35-972a-9d61eb256508"
    DISABLEHTTPSREDIRECTION: true
    Logging__LogLevel__Default: debug
    Logging__LogLevel__System: debug
    Logging__LogLevel__Microsoft: debug
    VHSERVICES__BOOKINGSAPIRESOURCEID: https://vh-bookings-api.{{ .Values.global.environment }}.platform.hmcts.net
    VHSERVICES__BOOKINGSAPIURL: https://vh-bookings-api.{{ .Values.global.environment }}.platform.hmcts.net
    VHSERVICES__USERAPIRESOURCEID: https://vh-video-api.{{ .Values.global.environment }}.platform.hmcts.net
    VHSERVICES__USERAPIURL: https://vh-video-api.{{ .Values.global.environment }}.platform.hmcts.net
    VHSERVICES__VIDEOAPIRESOURCEID: https://vh-video-api.{{ .Values.global.environment }}.platform.hmcts.net
    VHSERVICES__VIDEOAPIURL: https://vh-video-api.{{ .Values.global.environment }}.platform.hmcts.net


