---
image: '${IMAGE_NAME}'
releaseNameOverride: ${RELEASE_NAME}
crons:
  - cronJobName: vh-anonymise-hearings-and-conferences-job-pr-${PR_NUMBER}
    schedule: "30 5 * * *"
    concurrencyPolicy: Forbid
    args: 
    - AnonymiseHearingsConferencesAndDeleteAadUsersJob

  - cronJobName: vh-clear-conference-message-history-job-pr-${PR_NUMBER}
    schedule: "0 * * * *"
    concurrencyPolicy: Forbid
    args: 
    - ClearConferenceInstantMessageHistoryJob

  - cronJobName: vh-clear-hearings-job-pr-${PR_NUMBER}
    schedule: "0 23 * * *"
    concurrencyPolicy: Forbid
    args:
    - ClearHearingsJob

  - cronJobName: vh-delete-audio-recording-applications-job-pr-${PR_NUMBER}
    schedule: "0 22 * * *"
    concurrencyPolicy: Forbid
    args:
    - DeleteAudioRecordingApplicationsJob
    
  - cronJobName: vh-get-judiciary-users-job-pr-${PR_NUMBER}
    schedule: "0 2 * * *"
    concurrencyPolicy: Forbid
    args:
    - GetJudiciaryUsersJob

  - cronJobName: vh-reconcile-hearing-audio-with-storage-job-pr-${PR_NUMBER}
    schedule: "0 22 * * *"
    concurrencyPolicy: Forbid
    args: 
    - ReconcileHearingAudioWithStorageJob

  - cronJobName: vh-remove-heartbeats-for-conferences-job-pr-${PR_NUMBER}
    schedule: "40 5 * * *"
    concurrencyPolicy: Forbid
    args:
    - RemoveHeartbeatsForConferencesJob

  - cronJobName: vh-send-hearing-notifications-job-pr-${PR_NUMBER}
    schedule: "0 10 * * *"
    concurrencyPolicy: Forbid
    args:
    - SendHearingNotificationsJob
      
  - cronJobName: vh-hearing-allocations-job-pr-${PR_NUMBER}
    schedule: "0 3 * * *"
    concurrencyPolicy: Forbid
    args:
    - HearingsAllocationJob

environment:
  VHSERVICES__BOOKINGSAPIURL: https://vh-bookings-api-pr-780.dev.platform.hmcts.net/